ALTER TABLE "purchase_order_items" ADD COLUMN "freeQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "purchase_order_items" ADD COLUMN "freeReceived" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "grn_items" ADD COLUMN "freeQty" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "grns" ADD COLUMN "freeUnits" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "grns" ADD COLUMN "freeValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
